language: ruby
rvm:
  - 1.9.3
  - jruby-19mode
  - 2.0.0

env:
  - LOB_API_KEY=test_0dc8d51e0acffcb1880e0f19c79b2f5b0cc

before_script:
  - bundle exec rake dev:setup
  - rm -rf spec/vcr_cassettes

script: bundle exec rake test
